# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1d23d115eacad6e6c75949ab505c0d609e0d6c7c8ff920a1df4c9dea7dd177d3acb354da3c2cc3d961dc39c6e4968a02f8d676ae9e06d4c807540d98b008cf9

test:
  secret_key_base: 730a0530fa256d46bebe69d43ca8dbdc2d4822f122b332bb20c7edc3dd17b9733f90a4fea8b2f6613edcab4e6e6c95ac4a8625236c3a38539f748a8d4f5f7d72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
